### ISSUE TITLE
Sentry dependency doesn't build with Xcode 16.0 Beta 1

### ISSUE THREAD

**Issue by leandroalonso** [Automattic/Automattic-Tracks-iOS#288]
## TO-DO

- [x] Wait for this [PR](https://github.com/getsentry/sentry-cocoa/issues/4050) to be merged in the Sentry repo
- [x] Wait for a new Sentry version to be released
- [x] Update dependency #289
- [x] Release a new version
